### PR TITLE
Update for latest Material Design Icons + Small Fixes & Improvements

### PR DESCRIPTION
**Pull request by wollac11**
- Updated endpoint for codepoints file
- Updated comment URLs to point to new site for Material Design icons
- Regenerated MaterialDesignIcons.cs to include new icons and updated comments
- Fixed output path for MaterialDesignIcons.cs
- Increased console output verbosity
- Made a few other small code tweaks/cleanups

### CODE REVIEW

**Comment by matthewrdev** [comment]
@wollac11 Thanks for the pull request and for updating the generator to handle the new URL!

The one thing we'll need to fix is the variable names in the output file that begin with number literals (EG: `1k`, `9kPlus` etc) as this doesn't compile in C#. 



I've worked around this before by using a dictionary to convert numeric names to valid names. See: https://github.com/matthewrdev/md2cs/blob/master/md2cs/Helpers/DotNetNameHelper.cs#L10

The following icon names will need a mapping entry:

```

       public const string 10k = "\ue951";

       public const string 10mp = "\ue952";

       public const string 11mp = "\ue953";

       public const string 12mp = "\ue954";

       public const string 13mp = "\ue955";

       public const string 14mp = "\ue956";

       public const string 15mp = "\ue957";

       public const string 16mp = "\ue958";

       public const string 17mp = "\ue959";

       public const string 18mp = "\ue95a";

       public const string 19mp = "\ue95b";
       
       public const string 1k = "\ue95c";

       public const string 1kPlus = "\ue95d";

       public const string 1xMobiledata = "\uefcd";

       public const string 20mp = "\ue95e";

       public const string 21mp = "\ue95f";

       public const string 22mp = "\ue960";

       public const string 23mp = "\ue961";

       public const string 24mp = "\ue962";

       public const string 2k = "\ue963";

       public const string 2kPlus = "\ue964";

       public const string 2mp = "\ue965";

       public const string 30fps = "\uefce";

       public const string 30fpsSelect = "\uefcf";

       public const string 360 = "\ue577";

       public const string Rotation3D = "\ue84d";

       public const string 3gMobiledata = "\uefd0";

       public const string 3k = "\ue966";

       public const string 3kPlus = "\ue967";

       public const string 3mp = "\ue968";

       public const string 3p = "\uefd1";

       public const string 4gMobiledata = "\uefd2";

       public const string 4gPlusMobiledata = "\uefd3";

       public const string 4k = "\ue072";

       public const string 4kPlus = "\ue969";

       public const string 4mp = "\ue96a";

       public const string 5g = "\uef38";

       public const string 5k = "\ue96b";

       public const string 5kPlus = "\ue96c";

       public const string 5mp = "\ue96d";

       public const string 60fps = "\uefd4";

       public const string 60fpsSelect = "\uefd5";

       public const string 6FtApart = "\uf21e";

       public const string 6k = "\ue96e";

       public const string 6kPlus = "\ue96f";

       public const string 6mp = "\ue970";

       public const string 7k = "\ue971";

       public const string 7kPlus = "\ue972";

       public const string 7mp = "\ue973";

       public const string 8k = "\ue974";

       public const string 8kPlus = "\ue975";

       public const string 8mp = "\ue976";

       public const string 9k = "\ue977";

       public const string 9kPlus = "\ue978";

       public const string 9mp = "\ue979";
```

Let me have a think about what appropriate names are for each of these and get back to you.

**Comment by wollac11** [comment]
> @wollac11 Thanks for the pull request and for updating the generator to handle the new URL!
> 
> The one thing we'll need to fix is the variable names in the output file that begin with number literals (EG: `1k`, `9kPlus` etc) as this doesn't compile in C#.
> 

Ah yes, good point! There are a couple of cases that might be worth just mapping specifically, but to make it more compatible with future changes/additions to the icon set, I think it might be sensible to handle it more generically by converting proceeding numbers in the names to word form.

I'll make an update with this and you can see what you think.

**Comment by matthewrdev** [comment]
Ah, the updated number to string literal logic is fantastic @wollac11.

Let me download the new file and retest that it compiles (it looks like it should) and then I'll accept the PR.

**Comment by matthewrdev** [comment]
Compiles fine now, thanks again for the pull request @wollac11!

Hope that this tool/file is useful for you :)

**Comment by wollac11** [comment]
No problem. Glad you like it. Yes, it is a very useful tool (which I only recently stumbled across) and helps me with some of my projects so it is good to get it fully working again! Thanks!

**Pull request merged**
